"""add skills to jobs

Revision ID: 3a12a22732e5
Revises: 
Create Date: 2026-09-20 13:22:05.071341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a12a22732e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('applied', 'under_review', 'interview_scheduled', 'shortlisted', 'offered', 'rejected'),
               type_=sa.Enum('applied', 'under_review', 'shortlisted', 'rejected', name='application_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'applied'"))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('industry')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('active', 'suspended'), server_default=sa.text("'active'"), nullable=False))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('industry', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('applied', 'under_review', 'shortlisted', 'rejected', name='application_status_enum'),
               type_=mysql.ENUM('applied', 'under_review', 'interview_scheduled', 'shortlisted', 'offered', 'rejected'),
               existing_nullable=False,
               existing_server_default=sa.text("'applied'"))

    # ### end Alembic commands ###
